[package]
name = "TWENTY_PACKAGE"
edition = "2024.beta"
license = "MIT"
authors = ["Jim Liu"]

[dependencies]
# Sui = { override = true, local = "../../../crates/sui-framework/packages/sui-framework" }
usdc = { git = "https://github.com/circlefin/stablecoin-sui.git", subdir = "packages/usdc", rev = "master" }

[addresses] 
TWENTY_PACKAGE = "0x0"